# Generated by Django 3.2.19 on 2023-06-16 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
