# Generated by Django 3.2.19 on 2023-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0002_auto_20230616_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='department',
            field=models.CharField(default='new', max_length=200),
            preserve_default=False,
        ),
    ]
