# Generated by Django 3.2.19 on 2023-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0003_emp_details_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='supervisor',
            field=models.CharField(default='Boss', max_length=200),
        ),
        migrations.AddField(
            model_name='emp_details',
            name='weekly_contact_hours',
            field=models.FloatField(default=40),
        ),
    ]
