# Generated by Django 3.2.19 on 2023-06-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0005_emp_details_name_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('break_one', models.CharField(max_length=200)),
                ('break_two', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='name_tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='emp_details',
            name='shift',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_scheduler_app.shift'),
        ),
    ]
