# Generated by Django 3.2.19 on 2023-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0006_auto_20230621_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='shift',
        ),
        migrations.AddField(
            model_name='emp_details',
            name='shift',
            field=models.ManyToManyField(blank=True, default='', null=True, to='emp_scheduler_app.Shift'),
        ),
    ]
