# Generated by Django 3.2.19 on 2023-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0007_auto_20230621_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='shift',
            field=models.ManyToManyField(blank=True, default='', to='emp_scheduler_app.Shift'),
        ),
    ]
