# Generated by Django 3.2.19 on 2023-06-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0008_alter_emp_details_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='shift',
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_scheduler_app.emp_details')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_scheduler_app.shift')),
            ],
        ),
        migrations.AddField(
            model_name='emp_details',
            name='shifts',
            field=models.ManyToManyField(through='emp_scheduler_app.Scheduled', to='emp_scheduler_app.Shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shifts',
            field=models.ManyToManyField(through='emp_scheduler_app.Scheduled', to='emp_scheduler_app.Emp_Details'),
        ),
    ]
