# Generated by Django 3.2.19 on 2023-06-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0009_auto_20230621_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled',
            old_name='emp_details',
            new_name='emp_detail',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='shifts',
            new_name='emp_detail',
        ),
    ]
