# Generated by Django 3.2.19 on 2023-06-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0011_shift_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='added_by',
        ),
    ]
