# Generated by Django 3.2.19 on 2023-06-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0015_alter_shift_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp_details',
            options={'ordering': ['last_name', 'first_name', 'department']},
        ),
        migrations.AlterModelOptions(
            name='scheduled',
            options={'ordering': ['shift', 'emp_detail']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time', 'name']},
        ),
    ]
