# Generated by Django 3.2.19 on 2023-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0016_auto_20230624_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
