# Generated by Django 3.2.19 on 2023-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0018_alter_emp_details_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='emp_details',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='emp_details',
            name='manager',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
