# Generated by Django 3.2.19 on 2023-06-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0019_auto_20230624_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='manager',
        ),
        migrations.AddField(
            model_name='emp_details',
            name='Manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp_scheduler_app.manager'),
            preserve_default=False,
        ),
    ]
