# Generated by Django 3.2.19 on 2023-07-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0020_auto_20230624_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={},
        ),
    ]
