# Generated by Django 3.2.19 on 2023-07-16 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0022_alter_shift_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='schedule_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
