# Generated by Django 3.2.19 on 2023-07-23 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_scheduler_app', '0024_scheduled_schedule_date_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='schedule_date_select',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
